# Site settings
title: The Wibesmen
email: nybergica777@gmail.com
description: Go Wibesmen!
baseurl: "http://ryan258.github.io/thewibesmen/" # the subpath of your site, e.g. /blog/
url: "http://thewibesmen.com" # the base hostname & protocol for your site

#Social Settings
soundcloud: https://soundcloud.com/
facebook: TheWibesmen
youtube: https://www.youtube.com/
twitter_username: thewibesmen

# Build settings
markdown: kramdown
