# Site settings
title: The Wibesmen
email: nybergica777@gmail.com
description: Go Wibesmen!
baseurl: "http://ryan258.github.io/thewibesmen/" # the subpath of your site, e.g. /blog/
url: "http://thewibesmen.com" # the base hostname & protocol for your site

#Social Settings
soundcloud: https://soundcloud.com/
facebook: https://www.facebook.com/TheWibesmen
youtube: https://www.youtube.com/channel/UC6mu32alZTjf9_A1WeMzkeA
twitter_username: https://www.twitter.com/thewibesmen

# Build settings
markdown: kramdown
