# Site settings
title: The Wibesmen
email: nybergica777@gmail.com
description: Go Wibesmen!
baseurl: "http://ryan258.github.io/thewibesmen/" # the subpath of your site, e.g. /blog/
url: "http://thewibesmen.com" # the base hostname & protocol for your site

#Social Settings
soundcloud: https://soundcloud.com/
facebook: https://www.facebook.com/
youtube: https://www.youtube.com/channel/UCfND1vy3tgvxS2GO7gfdqEQ
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
